name: 'Feature Request'
description: 'Suggest any idea for this project'
title: '[FEATURE] '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Please search for open/closed issues before submitting. Someone
        might have asked the same thing before!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the feature.
      placeholder: |
        I would like to have the ability to ____.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are we doing this? What use cases does it support? What is the expected outcome?
      placeholder: |
        I want to be able to ____ because ____.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A brief description of the proposed solution.
      placeholder: |
        I think we should do this by ____.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A brief description of any alternative solutions or features you've considered.
      placeholder: |
        I have considered ____.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Additional information about the feature.
      placeholder: |
        I would like to be able to ____ because ____.
    validations:
      required: false

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: I have read and agree the follow the [EpycSolutions Code of Conduct](https://github.com/EpycSolutionsEU/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I understand that this project is licensed under the EpycSolutions Public Source License
          required: true