name: 'Documentation Request'
description: 'Suggest any idea for this project'
title: '[DOCS] '
labels: ['documentation']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation request!

        Please search for open/closed issues before submitting. Someone
        might have asked the same thing before!
  - type: textarea
    id: area
    attributes:
      label: Area
      description: The area of the documentation you want to request.
      placeholder: |
        I would like to request documentation for the ____ area.
    validations:
      required: true
  - type: 'textarea'
    id: 'current-issue'
    attributes:
      label: Current Issue
      description: What is currently missing, unclear, or incorrect in the documentation.
      placeholder: |
        The current documentation for ____ is ____.
    validations:
      required: true
  - type: 'textarea'
    id: 'suggested-improvment'
    attributes:
      label: Suggested Improvement
      description: What would you like to see improved or added in the documentation.
      placeholder: |
        I would like to see ____ improved or added in the documentation.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why this matters?
      description: Why is this important to you? What use cases does it support? What is the expected outcome?
      placeholder: |
        I want to be able to ____ because ____.
    validations:
      required: true
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: Additional information
      description: Additional information about the documentation request.
      placeholder: |
        I have considered ____.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: I have read and agree the follow the [EpycSolutions Code of Conduct](https://github.com/EpycSolutionsEU/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I understand that this project is licensed under the EpycSolutions Public Source License
          required: true